version: '3.8'

services:
  api: 
    container_name: api
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    command: npm run start:dev
    networks:
      - app-network
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  mongo:
    container_name: mongo
    image: mongo
    networks:
      - app-network
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db
    restart: unless-stopped
networks:
  app-network:
    name: app-network
    driver: bridge
volumes:
  dbdata: